export type QuizQuestion = {
  q: string;
  options: string[];
  answer: number;
  explanation: string;
};

export type FormulaRow = {
  formula: string;
  label: string;
  note?: string;
};

export type QuizCategory = {
  id: string;
  label: string;
  emoji: string;
  color: string;
  questions: QuizQuestion[];
  cheatSheet?: { title: string; rows: FormulaRow[] };
};

// ─────────────────────────────────────────────────────────────────────────────
// ÉLECTRONIQUE — 65 questions
// ─────────────────────────────────────────────────────────────────────────────
const Q_ELECTRONICS: QuizQuestion[] = [
  { q: "Quelle est la loi d'Ohm ?", options: ["P = U × I", "U = R × I", "R = P / I²", "I = P × U"], answer: 1, explanation: "U = R × I : la tension est égale à la résistance multipliée par le courant." },
  { q: "Quelle unité mesure la résistance ?", options: ["Volt (V)", "Ampère (A)", "Watt (W)", "Ohm (Ω)"], answer: 3, explanation: "La résistance se mesure en Ohm (Ω)." },
  { q: "Une LED nécessite toujours…", options: ["Une bobine en série", "Une résistance en série", "Un condensateur en parallèle", "Rien d'autre"], answer: 1, explanation: "Sans résistance série, le courant n'est pas limité et la LED grille." },
  { q: "En série, la résistance équivalente est…", options: ["R1 × R2", "R1 × R2 / (R1+R2)", "R1 + R2", "1/(1/R1 + 1/R2)"], answer: 2, explanation: "En série : Req = R1 + R2." },
  { q: "Quelle formule donne la puissance ?", options: ["P = R / I", "P = U + I", "P = U × I", "P = U / R²"], answer: 2, explanation: "P = U × I, aussi P = R × I² ou P = U² / R." },
  { q: "La constante de temps RC est…", options: ["τ = R + C", "τ = R / C", "τ = R × C", "τ = C / R"], answer: 2, explanation: "τ = R × C en secondes. À t = τ, le condensateur est chargé à ~63%." },
  { q: "Un transistor NPN en saturation se comporte comme…", options: ["Un interrupteur ouvert", "Une résistance élevée", "Un interrupteur fermé", "Une diode"], answer: 2, explanation: "En saturation, le transistor est complètement passant (interrupteur fermé)." },
  { q: "La diode Zener est utilisée pour…", options: ["Amplifier un signal", "Réguler une tension", "Stocker de l'énergie", "Mesurer le courant"], answer: 1, explanation: "La Zener maintient une tension quasi-constante en polarisation inverse." },
  { q: "Dans un diviseur de tension, Vout = ?", options: ["Vin × R1/(R1+R2)", "Vin × R2/(R1+R2)", "Vin / (R1 × R2)", "Vin + R2/R1"], answer: 1, explanation: "Vout = Vin × R2/(R1+R2). R2 est côté GND." },
  { q: "La loi des mailles dit que…", options: ["ΣI entrant = sortant", "ΣU dans une maille = 0", "Req est minimale", "I est constant"], answer: 1, explanation: "Kirchhoff (mailles) : la somme algébrique des tensions dans une maille = 0." },
  { q: "En parallèle, la résistance équivalente est…", options: ["R1 + R2", "R1 × R2", "(R1 × R2)/(R1+R2)", "R1 - R2"], answer: 2, explanation: "Pour deux résistances en parallèle : Req = (R1 × R2)/(R1+R2)." },
  { q: "À t = 5τ, le condensateur est chargé à…", options: ["63%", "86%", "95%", "99%"], answer: 3, explanation: "À t = 5τ, le condensateur est considéré chargé à ~99%." },
  { q: "La tension de seuil d'une diode silicium est environ…", options: ["0.1 V", "0.3 V", "0.7 V", "1.4 V"], answer: 2, explanation: "Une diode silicium conduit à partir d'environ 0.7 V." },
  { q: "Le courant dans un circuit série est…", options: ["Différent dans chaque composant", "Le même partout", "Nul dans les résistances", "Maximal dans la source"], answer: 1, explanation: "En série, le courant est identique dans tous les composants." },
  { q: "Un condensateur de 10 µF chargé sous 5 V stocke une charge de…", options: ["2 µC", "50 µC", "0.5 mC", "5 C"], answer: 1, explanation: "Q = C × U = 10×10⁻⁶ × 5 = 50 µC." },
  { q: "Le gain en courant β d'un BJT est typiquement…", options: ["1 à 5", "10 à 20", "50 à 500", "1000 à 5000"], answer: 2, explanation: "β (hFE) est typiquement entre 50 et 500 selon le transistor." },
  { q: "Ic = β × Ib signifie…", options: ["Le courant collecteur contrôle la base", "Le courant de base amplifié donne le courant collecteur", "Ib et Ic sont égaux", "Le courant émetteur est nul"], answer: 1, explanation: "Le BJT amplifie le courant : Ic = β × Ib en mode actif." },
  { q: "La loi des nœuds (KCL) dit que…", options: ["ΣU = 0", "ΣI entrant = ΣI sortant", "R = U/I", "P = U²/R"], answer: 1, explanation: "KCL : en tout nœud, la somme des courants entrants = sortants." },
  { q: "Un filtre passe-bas RC laisse passer…", options: ["Les hautes fréquences", "Toutes les fréquences", "Les basses fréquences", "Aucune fréquence"], answer: 2, explanation: "Filtre passe-bas : laisse les basses fréquences, coupe les hautes (fc = 1/(2πRC))." },
  { q: "La fréquence de coupure d'un filtre RC est…", options: ["fc = R × C", "fc = 1/(R × C)", "fc = 1/(2π × R × C)", "fc = 2π/(R × C)"], answer: 2, explanation: "fc = 1/(2πRC). À fc, le signal est atténué à 70.7% (−3 dB)." },
  { q: "L'unité de la capacité électrique est…", options: ["Henry (H)", "Farad (F)", "Tesla (T)", "Weber (Wb)"], answer: 1, explanation: "La capacité se mesure en Farad (F). En pratique : µF, nF ou pF." },
  { q: "L'énergie stockée dans un condensateur est…", options: ["E = C × U", "E = ½ C × U²", "E = C²× U", "E = U / C"], answer: 1, explanation: "E = ½ × C × U² en joules." },
  { q: "Une résistance de 1 kΩ traversée par 10 mA dissipe…", options: ["0.1 W", "0.01 W", "10 W", "1 W"], answer: 0, explanation: "P = R × I² = 1000 × (0.01)² = 0.1 W." },
  { q: "Quelle est la résistance pour une LED rouge (Vf=2V, I=20mA) sur 5V ?", options: ["100 Ω", "150 Ω", "250 Ω", "350 Ω"], answer: 1, explanation: "R = (Vcc - Vf) / I = (5-2)/0.02 = 150 Ω." },
  { q: "Le montage inverseur AOP a un gain de…", options: ["R1/R2", "-R2/R1", "1 + R2/R1", "R2/(R1+R2)"], answer: 1, explanation: "Av = -R2/R1 (le signe - indique l'inversion de phase)." },
  { q: "Un suiveur de tension AOP a un gain de…", options: ["-1", "0", "1", "∞"], answer: 2, explanation: "Le suiveur (buffer) a Av = 1 : Vout = Vin. Très haute impédance d'entrée." },
  { q: "La tension Vce d'un BJT saturé est approximativement…", options: ["0 V", "0.2 V", "0.7 V", "Vcc"], answer: 1, explanation: "En saturation, Vce_sat ≈ 0.2 V. Le transistor se comporte comme un interrupteur fermé." },
  { q: "Une diode Schottky a un seuil de conduction de…", options: ["0.2–0.4 V", "0.7 V", "1.2 V", "3.3 V"], answer: 0, explanation: "La Schottky conduit dès 0.2–0.4 V (moins que le silicium) et commute très vite." },
  { q: "La puissance d'un circuit consommant 2A sous 12V est…", options: ["6 W", "14 W", "24 W", "144 W"], answer: 2, explanation: "P = U × I = 12 × 2 = 24 W." },
  { q: "Que fait une diode de roue libre ?", options: ["Amplifie le courant", "Protège contre les surtensions d'une bobine", "Filtre les signaux AC", "Stabilise la tension Zener"], answer: 1, explanation: "La diode de roue libre protège le circuit contre la surtension générée lors de la coupure d'une bobine (relais, moteur)." },
  { q: "R1 = 100 Ω, R2 = 100 Ω en série. La résistance totale est…", options: ["50 Ω", "100 Ω", "200 Ω", "10 kΩ"], answer: 2, explanation: "En série : Req = R1 + R2 = 100 + 100 = 200 Ω." },
  { q: "R1 = 100 Ω, R2 = 100 Ω en parallèle. Req = ?", options: ["200 Ω", "100 Ω", "50 Ω", "25 Ω"], answer: 2, explanation: "Req = (100×100)/(100+100) = 10000/200 = 50 Ω." },
  { q: "Quelle tension obtient-on avec un diviseur Vin=12V, R1=3kΩ, R2=1kΩ ?", options: ["3 V", "4 V", "6 V", "9 V"], answer: 0, explanation: "Vout = 12 × 1/(3+1) = 12 × 0.25 = 3 V." },
  { q: "Dans un montage non-inverseur AOP avec R1=1kΩ, R2=9kΩ, le gain est…", options: ["9", "10", "-9", "-10"], answer: 1, explanation: "Av = 1 + R2/R1 = 1 + 9 = 10 (positif, non-inverseur)." },
  { q: "Un condensateur bloque…", options: ["Le courant alternatif (AC)", "Le courant continu (DC)", "Les signaux haute fréquence", "Les signaux basse amplitude"], answer: 1, explanation: "Un condensateur bloque le DC (courant continu) et laisse passer l'AC. Son impédance = 1/(2πfC)." },
  { q: "La période T d'un signal à 50 Hz est…", options: ["50 ms", "20 ms", "2 ms", "0.02 ms"], answer: 1, explanation: "T = 1/f = 1/50 = 0.02 s = 20 ms." },
  { q: "L'impédance d'un condensateur augmente quand la fréquence…", options: ["Augmente", "Diminue", "Reste constante", "Double uniquement"], answer: 1, explanation: "Zc = 1/(2πfC) : quand f diminue, Zc augmente. Le condensateur bloque les basses fréquences." },
  { q: "Une bobine (inductance) s'oppose aux…", options: ["Variations de tension", "Variations brusques de courant", "Signaux DC", "Surtensions Zener"], answer: 1, explanation: "uL = L × (di/dt) : la bobine génère une tension proportionnelle à la variation du courant." },
  { q: "La tension Vbe d'un transistor NPN en conduction est…", options: ["0 V", "0.3 V", "0.7 V", "1.4 V"], answer: 2, explanation: "Vbe ≈ 0.7 V pour un transistor silicium NPN (comme une diode polarisée en direct)." },
  { q: "Un MOSFET est commandé par…", options: ["Un courant de base", "Une tension grille-source (Vgs)", "Un courant de drain", "La température"], answer: 1, explanation: "Le MOSFET est commandé en tension Vgs. Aucun courant de grille n'est nécessaire." },
  { q: "Quelle est la fréquence de coupure si R=10kΩ et C=15.9nF ?", options: ["100 Hz", "1 kHz", "10 kHz", "100 kHz"], answer: 1, explanation: "fc = 1/(2π×10000×15.9×10⁻⁹) ≈ 1/(2π×159×10⁻⁶) ≈ 1000 Hz = 1 kHz." },
  { q: "Un filtre passe-haut RC atténue…", options: ["Les hautes fréquences", "Le signal à fc de 3 dB", "Les basses fréquences (dont le DC)", "Rien, il n'atténue pas"], answer: 2, explanation: "Passe-haut : coupe les basses fréquences (DC compris), laisse passer les hautes." },
  { q: "À la fréquence de coupure fc, le signal est atténué de…", options: ["0 dB", "3 dB", "6 dB", "20 dB"], answer: 1, explanation: "À fc : atténuation de −3 dB, soit 70.7% de l'amplitude (facteur 1/√2)." },
  { q: "Quel composant stocke de l'énergie dans un champ magnétique ?", options: ["Condensateur", "Résistance", "Bobine (inductance)", "Diode Zener"], answer: 2, explanation: "La bobine stocke l'énergie sous forme de champ magnétique : E = ½ × L × I²." },
  { q: "La résistance interne idéale d'une source de tension est…", options: ["Infinie", "Nulle", "Égale à la charge", "100 Ω"], answer: 1, explanation: "Une source de tension idéale a une résistance interne nulle (Vout constant quelle que soit la charge)." },
  { q: "Deux résistances 47Ω en parallèle donnent…", options: ["94 Ω", "47 Ω", "23.5 Ω", "11.75 Ω"], answer: 2, explanation: "Req = (47×47)/(47+47) = 2209/94 = 23.5 Ω (moitié pour deux résistances identiques en parallèle)." },
  { q: "Quel mode d'un transistor BJT correspond à l'amplification ?", options: ["Mode bloqué", "Mode saturé", "Mode actif", "Mode Zener"], answer: 2, explanation: "En mode actif (linéaire), le BJT amplifie : Ic = β × Ib, sans saturation ni blocage." },
  { q: "Si Vin = 1V et le gain AOP = -5, Vout = ?", options: ["+5 V", "-5 V", "+0.2 V", "-0.2 V"], answer: 1, explanation: "Vout = Av × Vin = -5 × 1 = -5 V. L'inverseur AOP inverse et amplifie." },
  { q: "La fréquence du secteur en France est…", options: ["50 Hz", "60 Hz", "100 Hz", "400 Hz"], answer: 0, explanation: "Le réseau électrique français (et européen) est à 50 Hz, 230 V efficace." },
  { q: "La tension efficace (RMS) du secteur en France est…", options: ["110 V", "163 V", "230 V", "325 V"], answer: 2, explanation: "230 V efficace (RMS). La tension crête est 230 × √2 ≈ 325 V." },
  { q: "Un redresseur double alternance utilise…", options: ["1 diode", "2 diodes", "4 diodes (pont de Graetz)", "Un transistor"], answer: 2, explanation: "Le pont de Graetz (4 diodes) redresse les deux alternances du signal AC." },
  { q: "L'énergie stockée dans une bobine L=100mH, I=2A est…", options: ["0.1 J", "0.2 J", "0.4 J", "2 J"], answer: 1, explanation: "E = ½ × L × I² = ½ × 0.1 × 4 = 0.2 J." },
  { q: "Quelle résistance dissipe 0.25W sous 5V ?", options: ["20 Ω", "50 Ω", "100 Ω", "200 Ω"], answer: 2, explanation: "P = U²/R → R = U²/P = 25/0.25 = 100 Ω." },
  { q: "Un AOP comparateur sans contre-réaction…", options: ["Suit l'entrée avec Av=1", "Sature en haute ou basse tension", "Intègre le signal", "A un gain de R2/R1"], answer: 1, explanation: "Sans rétroaction, l'AOP est comparateur : sature à ±Vcc selon que V+ > V− ou non." },
  { q: "La pente d'atténuation d'un filtre RC 1er ordre est…", options: ["-6 dB/octave", "-20 dB/décade", "Les deux réponses sont correctes", "Aucune des deux"], answer: 2, explanation: "-20 dB/décade = -6 dB/octave : c'est la même pente, deux façons de l'exprimer." },
  { q: "La résistance de base pour piloter un transistor NPN (Ic=100mA, β=100, Vcmd=5V) est…", options: ["47 Ω", "500 Ω", "4.3 kΩ", "43 kΩ"], answer: 1, explanation: "Ib = Ic/(β/10) = 100mA/10 = 10mA. Rb = (5-0.7)/0.01 = 430 Ω → ~470 Ω. On prend ~500 Ω avec marge." },
  { q: "Que mesure un wattmètre ?", options: ["La tension", "Le courant", "La puissance active", "La résistance"], answer: 2, explanation: "Le wattmètre mesure la puissance active (en watts) consommée par un circuit." },
  { q: "L'impédance d'une bobine augmente quand la fréquence…", options: ["Diminue", "Augmente", "Est nulle", "Est égale à fc"], answer: 1, explanation: "ZL = 2πfL : l'impédance de la bobine augmente avec la fréquence (inverse du condensateur)." },
  { q: "Vout d'un montage non-inverseur avec Vin=2V, R1=2kΩ, R2=8kΩ ?", options: ["2 V", "8 V", "10 V", "4 V"], answer: 2, explanation: "Av = 1 + 8/2 = 5. Vout = 5 × 2 = 10 V." },
  { q: "Un pont diviseur Vin=9V, R1=2kΩ, R2=1kΩ → Vout = ?", options: ["1 V", "2 V", "3 V", "6 V"], answer: 2, explanation: "Vout = 9 × 1/(2+1) = 9/3 = 3 V." },
  { q: "La règle d'or de l'AOP idéal en rétroaction : V+ − V− = ?", options: ["Vout/β", "0 V", "0.7 V", "Vcc/2"], answer: 1, explanation: "Pour un AOP idéal en boucle fermée : V+ = V− (tension différentielle nulle)." },
  { q: "Quel composant est utilisé pour générer une tension de référence stable ?", options: ["Résistance", "Condensateur", "Diode Zener", "Bobine"], answer: 2, explanation: "La diode Zener maintient une tension stable Vz en polarisation inverse : sert de référence." },
  { q: "Un circuit RLC série résonne quand…", options: ["f = RC", "XL = XC (impédances égales)", "R = L × C", "La tension est maximale"], answer: 1, explanation: "Résonance série : XL = XC, soit 2πfL = 1/(2πfC). À f0, l'impédance est minimale (= R seul)." },
  { q: "Quel est le courant si R=470Ω et U=4.7V ?", options: ["10 µA", "100 µA", "10 mA", "100 mA"], answer: 2, explanation: "I = U/R = 4.7/470 = 0.01 A = 10 mA." },
];

// ─────────────────────────────────────────────────────────────────────────────
// MAINTENANCE — 62 questions
// ─────────────────────────────────────────────────────────────────────────────
const Q_MAINTENANCE: QuizQuestion[] = [
  { q: "En mode voltmètre, le multimètre se branche…", options: ["En série", "En parallèle", "Sur la borne ampère", "Entre phase et neutre uniquement"], answer: 1, explanation: "Voltmètre : en parallèle (~10 MΩ d'impédance)." },
  { q: "En mode ampèremètre, le multimètre se branche…", options: ["En parallèle", "Sans toucher le circuit", "En série après avoir ouvert le circuit", "Sur les bornes de tension"], answer: 2, explanation: "Ampèremètre : en série dans le circuit ouvert (impédance quasi nulle)." },
  { q: "Que signifie VAT ?", options: ["Valeur de Alimentation Totale", "Vérification d'Absence de Tension", "Voltmètre Auto-Testeur", "Validation par Agent Technique"], answer: 1, explanation: "VAT = Vérification d'Absence de Tension. Étape obligatoire avant tout travail hors tension." },
  { q: "Une soudure froide est reconnaissable à son aspect…", options: ["Brillant et lisse", "Terne et grumeleuse", "Sphérique parfaite", "Transparente"], answer: 1, explanation: "Terne et grumeleuse = soudure froide (mauvaise mouillabilité)." },
  { q: "Comment tester une diode au multimètre ?", options: ["Mode tension AC", "Mode diode, lire ~0.5-0.7V", "Mode continuité, bip dans les deux sens", "Mode résistance, lire kΩ"], answer: 1, explanation: "Mode diode : affiche la chute de tension directe (~0.5-0.7V Si). '1' dans les deux sens = diode claquée." },
  { q: "Un condensateur électrolytique bombé est…", options: ["Normal en fonctionnement chaud", "Défaillant, à remplacer", "Simplement saturé", "Un signe de surcharge passager"], answer: 1, explanation: "Condensateur bombé = DÉFAILLANT. À remplacer immédiatement." },
  { q: "La méthode de diagnostic par dichotomie consiste à…", options: ["Tout remplacer", "Diviser le circuit en deux et tester le milieu", "Mesurer uniquement l'alim", "Contrôler les composants un par un du début"], answer: 1, explanation: "Dichotomie : diviser en deux, tester le milieu, recommencer jusqu'à isoler la panne." },
  { q: "Température de soudure pour l'étain sans plomb SAC305 ?", options: ["150-200°C", "220-260°C", "320-380°C", "400-450°C"], answer: 2, explanation: "SAC305 : 320-380°C (point de fusion ~217°C + marge). Étain plombé Sn63 : 280-320°C." },
  { q: "L'habilitation B1 permet de…", options: ["Consigner des ouvrages", "Travailler hors tension en BT", "Superviser sans toucher", "Intervenir sur HTA"], answer: 1, explanation: "B1 : travailler hors tension sur des ouvrages BT après consignation." },
  { q: "IP65 signifie…", options: ["Protégé poussière + jets d'eau", "Immersion 1m/30min", "Non protégé eau", "Usage maritime uniquement"], answer: 0, explanation: "IP65 : 6 = étanche poussière, 5 = jets d'eau toutes directions." },
  { q: "Les 5 règles de sécurité hors tension : la 3e est…", options: ["Consigner", "Séparer", "VAT (Vérification d'Absence de Tension)", "Baliser"], answer: 2, explanation: "Ordre : Séparer → Condamner → VAT → Mettre à la terre → Baliser." },
  { q: "Le mode continuité (buzzer) du multimètre bipe si la résistance est…", options: ["Infinie", "Supérieure à 1 MΩ", "Inférieure à quelques ohms", "Exactement 0 Ω"], answer: 2, explanation: "Le buzzer bipe si la résistance entre les pointes est < quelques ohms (circuit continu)." },
  { q: "Qu'est-ce qu'un circuit ouvert ?", options: ["Un circuit sans résistance", "Une rupture dans la continuité électrique", "Un court-circuit", "Un circuit alimenté"], answer: 1, explanation: "Circuit ouvert = rupture : le courant ne peut plus circuler." },
  { q: "Qu'est-ce qu'un court-circuit ?", options: ["Un circuit correct", "Une connexion non voulue à faible résistance", "Un circuit sans condensateur", "Un filtre passe-bas"], answer: 1, explanation: "Court-circuit = connexion involontaire à résistance quasi nulle → courant excessif, risque de destruction." },
  { q: "Pour mesurer une résistance au multimètre, le composant doit être…", options: ["Sous tension", "En fonctionnement normal", "Hors tension et déconnecté du circuit", "Traversé par un courant connu"], answer: 2, explanation: "Mesure de résistance : toujours hors tension et idéalement déconnecté du circuit." },
  { q: "Un composant anormalement chaud au toucher indique souvent…", options: ["Un fonctionnement normal", "Une surcharge ou un défaut en aval", "Une bonne conduction", "Un gain élevé"], answer: 1, explanation: "Un composant trop chaud est souvent en surcharge : court-circuit aval, valeur incorrecte ou composant défaillant." },
  { q: "La tension dangereuse pour l'homme commence à…", options: ["12 V AC", "25 V AC", "110 V AC", "230 V AC"], answer: 1, explanation: "Seuil de danger : 25 V AC ou 60 V DC (norme IEC 60479)." },
  { q: "La résistance du corps humain (peau sèche) est environ…", options: ["10 Ω", "100 Ω", "1 000 Ω", "1 MΩ"], answer: 2, explanation: "Peau sèche : ~1000 Ω. Peau humide : ~500 Ω. C'est pourquoi les risques électriques augmentent en milieu humide." },
  { q: "Le courant de tétanisation est atteint à environ…", options: ["0.5 mA", "10 mA", "100 mA", "1 A"], answer: 1, explanation: "10 mA : seuil de tétanisation (impossibilité de lâcher). 100 mA : risque de fibrillation cardiaque mortelle." },
  { q: "Comment s'appelle la norme française des installations BT ?", options: ["NF C 15-100", "IEC 60479", "IP 65", "NF EN 50110"], answer: 0, explanation: "NF C 15-100 : norme française de référence pour les installations électriques basse tension." },
  { q: "Quelle couleur désigne le conducteur de terre en France ?", options: ["Bleu", "Brun", "Vert/Jaune", "Noir"], answer: 2, explanation: "Vert/Jaune = conducteur de terre (PE). Bleu = neutre. Brun/Noir/Rouge = phase." },
  { q: "La soudure en forme de cône volcanique autour de la patte est…", options: ["Une mauvaise soudure", "Une soudure correcte", "Signe de surchauffe", "Signe de flux insuffisant"], answer: 1, explanation: "Un bon joint de soudure est en forme de cône, brillant (Sn/Pb) et bien mouillé sur la patte et le pad." },
  { q: "Pourquoi ajouter du flux avant de dessouder ?", options: ["Pour refroidir", "Pour améliorer la fluidité et le mouillage de l'étain", "Pour nettoyer le PCB", "Pour éviter les ponts de soudure"], answer: 1, explanation: "Le flux contient des agents désoxydants qui améliorent la fluidité de l'étain et facilitent la dessoudure." },
  { q: "La tresse à dessouder fonctionne par…", options: ["Aspiration mécanique", "Capillarité : absorbe l'étain fondu", "Évaporation de l'étain", "Dissolving chimique"], answer: 1, explanation: "La tresse absorbe l'étain fondu par capillarité lorsqu'on la chauffe avec le fer." },
  { q: "L'oscilloscope affiche…", options: ["La résistance en fonction du temps", "La tension en fonction du temps", "Le courant uniquement", "La puissance instantanée"], answer: 1, explanation: "L'oscilloscope affiche Vin (tension) en fonction du temps. Idéal pour analyser des signaux variables." },
  { q: "La base de temps (Time/Div) de l'oscilloscope règle…", options: ["L'amplitude verticale du signal", "L'échelle temporelle horizontale", "Le seuil de déclenchement", "Le couplage AC/DC"], answer: 1, explanation: "Time/Div : échelle de l'axe X (temps). V/Div : échelle de l'axe Y (tension)." },
  { q: "Le trigger (déclenchement) de l'oscilloscope sert à…", options: ["Amplifier le signal", "Stabiliser l'affichage en synchronisant la base de temps", "Filtrer les hautes fréquences", "Mesurer la fréquence automatiquement"], answer: 1, explanation: "Le trigger stabilise l'affichage en déclenchant le balayage à un niveau de signal défini." },
  { q: "La sonde × 10 de l'oscilloscope…", options: ["Amplifie le signal ×10", "Divise le signal affiché par 10", "Filtre les harmoniques", "Mesure le courant"], answer: 1, explanation: "Sonde ×10 : atténue le signal par 10 pour protéger l'oscilloscope et mesurer des tensions plus élevées." },
  { q: "IP44 convient pour…", options: ["Immersion prolongée", "Extérieur sous la pluie battante", "Atelier standard (projections)", "Usage médical stérile"], answer: 2, explanation: "IP44 : 4 = corps solides >1mm, 4 = projections d'eau. Convient à un atelier standard." },
  { q: "Classe II d'un équipement signifie…", options: ["Nécessite une mise à la terre", "Double isolation, pas besoin de terre", "Très basse tension (< 50 V)", "Usage industriel uniquement"], answer: 1, explanation: "Classe II : double isolation (symbole carré dans carré). Pas de borne de terre nécessaire." },
  { q: "Un composant 'claqué' en circuit ouvert au multimètre en mode Ω affiche…", options: ["0 Ω", "Sa valeur nominale", "Hors calibre (OL / 1)", "−1"], answer: 2, explanation: "Un circuit ouvert affiche OL (Over Limit) ou '1' sur le multimètre : résistance infinie." },
  { q: "Comment identifier une soudure froide visuellement ?", options: ["Elle est plus brillante que les autres", "Elle est terne, grumeleuse, parfois fissurée", "Elle est plus grosse et lisse", "Elle est colorée en gris clair"], answer: 1, explanation: "Soudure froide : aspect terne, grumeleuse ou avec des craquelures (mauvaise mouillabilité, mouvement pendant refroidissement)." },
  { q: "La NF C 18-510 concerne…", options: ["Les PCB industriels", "Les habilitations électriques", "Les normes IP", "La norme EN ISO 9001"], answer: 1, explanation: "NF C 18-510 : norme française définissant les habilitations électriques (B0, B1, B2, BR, BC, H...)." },
  { q: "Lors de la mesure d'une tension AC avec le multimètre, il affiche…", options: ["La valeur crête", "La valeur crête-à-crête", "La valeur efficace (RMS)", "La valeur instantanée"], answer: 2, explanation: "Le multimètre en AC affiche la valeur efficace (RMS). Ex : 230 V sur le secteur." },
  { q: "Umax du secteur (230 V RMS) est…", options: ["163 V", "230 V", "270 V", "325 V"], answer: 3, explanation: "Umax = Ueff × √2 = 230 × 1.414 ≈ 325 V." },
  { q: "Une résistance mesurée hors circuit affiche 0 Ω. C'est…", options: ["Normal pour une petite résistance", "Signe de court-circuit (résistance claquée)", "Signe de circuit ouvert", "Valeur correcte pour 1 Ω"], answer: 1, explanation: "0 Ω sur une résistance hors circuit indique un court-circuit interne (résistance claquée en court)." },
  { q: "Pourquoi met-on une diode de roue libre sur un relais ?", options: ["Pour amplifier la commande", "Pour protéger le transistor de la surtension", "Pour réduire la résistance de bobine", "Pour augmenter le courant de commande"], answer: 1, explanation: "La coupure du courant dans la bobine du relais génère une surtension inversée qui détruirait le transistor de commande." },
  { q: "Qu'est-ce qu'un ESR élevé sur un condensateur électrolytique ?", options: ["Résistance série équivalente élevée → condensateur dégradé", "Condensateur chargé à 100%", "Bonne qualité de filtrage", "Capacité plus grande que nominale"], answer: 0, explanation: "ESR (Equivalent Series Resistance) élevé = condensateur dégradé. Cause des problèmes de filtrage et de chauffage." },
  { q: "Les EPI électriques obligatoires pour travailler en BT comprennent…", options: ["Lunettes solaires et casque", "Gants isolants et chaussures de sécurité", "Tenue de sport et masque", "Gants de jardinage"], answer: 1, explanation: "Gants isolants (classe 00 pour <500V), chaussures de sécurité isolantes, écran facial si risque d'arc." },
  { q: "Que signifie CEM ?", options: ["Compatibilité ÉlectroMagnétique", "Circuit Électronique Miniaturisé", "Courant Électrique Maximum", "Condensateur Électrolytique Marque"], answer: 0, explanation: "CEM : un équipement ne doit ni émettre de perturbations ni être perturbé par son environnement EM." },
  { q: "Lors d'un dépannage, quelle est la première vérification à faire ?", options: ["Remplacer le composant le plus cher", "Vérifier l'alimentation", "Dessouder tous les composants suspects", "Mesurer toutes les résistances"], answer: 1, explanation: "Toujours vérifier l'alimentation en premier : 80% des pannes viennent de là (fusible, tension, connexion)." },
  { q: "Le couplage AC de l'oscilloscope sert à…", options: ["Mesurer la composante DC uniquement", "Bloquer la composante DC pour voir les variations AC", "Amplifier le signal ×10", "Synchroniser le trigger"], answer: 1, explanation: "Couplage AC : le condensateur interne bloque le DC. On voit uniquement les variations du signal." },
  { q: "Pourquoi condamner (cadenasser) un disjoncteur avant de travailler ?", options: ["Pour économiser l'énergie", "Pour empêcher toute remise sous tension involontaire", "C'est une obligation esthétique", "Pour éviter les pertes en ligne"], answer: 1, explanation: "La consignation (cadenas + pancarte) empêche la remise sous tension accidentelle par une tierce personne." },
  { q: "Comment mesure-t-on la fréquence d'un signal à l'oscilloscope ?", options: ["Directement en Hz sur l'afficheur", "T = divisions × Time/div, puis f = 1/T", "En mode fréquencemètre uniquement", "Avec la sonde ×10"], answer: 1, explanation: "T (période) = nombre de divisions d'une période × Time/div. Puis f = 1/T." },
  { q: "Qu'est-ce qu'une 'soudure en pont' (solder bridge) ?", options: ["Une soudure sur un via", "Un excès d'étain reliant deux pads adjacents involontairement", "Une soudure sur un composant CMS", "Une soudure réalisée par vague"], answer: 1, explanation: "Solder bridge = pont d'étain entre deux pads : court-circuit. Éliminer avec tresse ou pompe." },
  { q: "Le fil de protection (terre, PE) est obligatoire pour les équipements…", options: ["Classe II", "Classe III", "Classe I", "Classe IV"], answer: 2, explanation: "Classe I : isolation simple + mise à la terre obligatoire. Classe II : double isolation, pas de terre." },
  { q: "Le multimètre indique 'OL' ou '1' en mode résistance. Cela signifie…", options: ["0 Ω (court-circuit)", "Résistance infinie (circuit ouvert)", "1 Ω exactement", "Batterie faible"], answer: 1, explanation: "OL (OverLimit) = dépassement de calibre = résistance trop grande = circuit ouvert." },
  { q: "Pour le mode soudure CMS, la pâte à braser contient…", options: ["De l'étain pur", "De l'étain en poudre + flux", "Du plomb seul", "De la colle epoxy conductrice"], answer: 1, explanation: "Pâte à braser = poudre d'alliage étain + flux. Déposée par sérigraphie ou dispenseur, puis refondue au four." },
  { q: "Une résistance R5 = 10 kΩ mesure 47 kΩ hors circuit. C'est…", options: ["Normal, résistance avec tolérance", "Résistance dérivée hors tolérance, à remplacer", "Résistance en court-circuit", "Erreur de mesure uniquement"], answer: 1, explanation: "47 kΩ pour une valeur nominale de 10 kΩ = dérive importante (>400%). Défaillance due à surchauffe ou vieillissement." },
  { q: "Quel est l'ordre des couleurs de l'anneau d'une résistance 470 Ω (4 bandes) ?", options: ["Jaune-Violet-Marron", "Vert-Violet-Marron", "Jaune-Violet-Rouge", "Vert-Bleu-Marron"], answer: 0, explanation: "470 = 4-7-×10¹ = Jaune (4), Violet (7), Marron (×10). 4ème bande = tolérance (Or=5%, Argent=10%)." },
  { q: "La sécurité d'un circuit électronique contre les inversions de polarité utilise souvent…", options: ["Un transistor NPN", "Une diode en série ou en pont", "Un condensateur", "Une résistance de shunt"], answer: 1, explanation: "Diode en série ou pont de diodes : bloque le courant si la polarité est inversée, protégeant le circuit." },
  { q: "Un test 'in-circuit' de résistance peut donner une valeur fausse car…", options: ["Le multimètre est trop précis", "Les composants parallèles en circuit modifient la mesure", "La résistance est trop froide", "Le PCB ajoute de la résistance"], answer: 1, explanation: "En circuit, d'autres résistances en parallèle réduisent la valeur mesurée. Toujours déconnecter une extrémité." },
  { q: "Qu'est-ce qu'une panne intermittente ?", options: ["Une panne permanente", "Une panne qui apparaît et disparaît (souvent liée à la température ou aux vibrations)", "Une panne très grave", "Une panne sur les alimentations uniquement"], answer: 1, explanation: "Intermittente : panne difficile à reproduire. Souvent : soudure froide, connexion desserrée ou composant sensible à la température." },
  { q: "Le courant maximal supporté par un fusible 500 mA est…", options: ["500 µA", "50 mA", "500 mA", "5 A"], answer: 2, explanation: "Un fusible 500 mA (0.5 A) se coupe si le courant dépasse 500 mA pendant un certain temps." },
  { q: "L'habilitation BR permet de…", options: ["Travailler sur HTA", "Effectuer du dépannage et des essais en BT", "Superviser un chantier électrique", "Concevoir des armoires électriques"], answer: 1, explanation: "BR : habilitation pour le dépannage, les essais et les mesures en basse tension." },
  { q: "Avant de remplacer un composant sur une carte en service, il faut…", options: ["Le remplacer directement sans couper l'alim", "Couper l'alimentation, décharger les condensateurs, puis intervenir", "Mesurer d'abord sous tension", "Rien de spécial"], answer: 1, explanation: "Couper l'alimentation, décharger les condensateurs (délai ou résistance de décharge), puis travailler en sécurité." },
  { q: "Les gants isolants de classe 00 protègent jusqu'à…", options: ["50 V", "500 V", "1000 V", "5000 V"], answer: 1, explanation: "Classe 00 : tension de travail max 500 V. Classe 0 : 1000 V. Classe 1 : 7500 V." },
  { q: "Qu'affiche le multimètre en mode diode sur une LED rouge fonctionnelle ?", options: ["0.3-0.5 V", "0.6-0.7 V", "1.8-2.2 V", "3.2-3.6 V"], answer: 2, explanation: "LED rouge : Vf ≈ 1.8-2.2 V. Bleue/blanche : 3.0-3.4 V. Si OL dans les deux sens = LED claquée." },
  { q: "Comment éviter les décharges électrostatiques (ESD) lors de la manipulation de composants ?", options: ["Porter des gants épais", "Utiliser un bracelet antistatique relié à la terre", "Travailler rapidement", "Humidifier l'air"], answer: 1, explanation: "Bracelet antistatique (ESD wrist strap) + tapis antistatique = protection contre les ESD qui détruisent silencieusement les CMOS et MOSFET." },
];

// ─────────────────────────────────────────────────────────────────────────────
// FABRICATION — 60 questions
// ─────────────────────────────────────────────────────────────────────────────
const Q_FABRICATION: QuizQuestion[] = [
  { q: "Que signifie PCB ?", options: ["Power Control Board", "Printed Circuit Board", "Passive Component Base", "Programmable Control Bus"], answer: 1, explanation: "PCB = Printed Circuit Board (Circuit Imprimé)." },
  { q: "Le substrat FR4 est composé de…", options: ["Aluminium et silicone", "Fibre de verre et résine époxy", "Bakélite et cuivre", "Céramique et polyimide"], answer: 1, explanation: "FR4 = fibre de verre tissée + résine époxy. Standard PCB basse fréquence." },
  { q: "Un via traversant relie…", options: ["Deux composants CMS", "Toutes les couches de haut en bas", "Le pad au composant THT", "La sérigraphie au vernis"], answer: 1, explanation: "Via traversant : trou métallisé qui traverse tout le PCB et relie toutes les couches." },
  { q: "CMS/SMD signifie…", options: ["Composant Multifonction Standard", "Composants Montés en Surface", "Circuit Miniaturisé Série", "Contrôle Mécanique de Surface"], answer: 1, explanation: "CMS (Surface Mount Device en anglais) : composants soudés directement sur les pads de surface." },
  { q: "Quel procédé assemble les CMS en production ?", options: ["Soudure à la vague", "Four de refusion (reflow)", "Soudure manuelle au fer", "Brasage fort"], answer: 1, explanation: "Reflow : dépôt pâte à braser → placement CMS → four (~245°C pic pour SAC305)." },
  { q: "Les fichiers Gerber servent à…", options: ["Simuler le circuit", "Décrire la fabrication du PCB pour l'usine", "Calculer les valeurs des composants", "Programmer les µC"], answer: 1, explanation: "Gerber : format standard pour la fabrication (couches cuivre, vernis, sérigraphie, perçage)." },
  { q: "La section 'Absolute Maximum Ratings' d'une datasheet donne…", options: ["Les valeurs typiques", "Le prix max du composant", "Les limites à ne jamais dépasser", "La fréquence max d'entrée"], answer: 2, explanation: "Absolute Maximum Ratings = limites absolues. Les dépasser détruit le composant." },
  { q: "La norme IPC-610 concerne…", options: ["Le perçage des PCB", "L'acceptabilité des assemblages électroniques", "La conception des schémas", "Les tensions de test"], answer: 1, explanation: "IPC-A-610 : critères d'acceptabilité des assemblages. Classes 1 (grand public), 2 (industriel), 3 (critique)." },
  { q: "Un composant 'tombstone' CMS est…", options: ["Claqué par surtension", "Soulevé d'un côté pendant le reflow", "Un condensateur qui explose", "Un court-circuit entre pads"], answer: 1, explanation: "Tombstoning : un CMS 2 broches se soulève d'un côté (tension de surface inégale au reflow)." },
  { q: "Le vernis épargne (solder mask) sert à…", options: ["Décorer le PCB", "Protéger les pistes et éviter les ponts de soudure", "Isoler thermiquement", "Identifier les couches"], answer: 1, explanation: "Solder mask : protège le cuivre de l'oxydation et empêche les ponts de soudure entre pads adjacents." },
  { q: "La sérigraphie (silkscreen) sur un PCB représente…", options: ["Les pistes de cuivre", "Les composants en couche", "Les repères et références des composants", "Les vias borgnes"], answer: 2, explanation: "Sérigraphie : impression (blanc généralement) des références (R1, C2, U1) et polarités sur le PCB." },
  { q: "L'épaisseur standard d'un PCB FR4 est…", options: ["0.4 mm", "0.8 mm", "1.6 mm", "3.2 mm"], answer: 2, explanation: "Épaisseur standard = 1.6 mm. D'autres épaisseurs existent (0.8, 2.4 mm) pour besoins spécifiques." },
  { q: "Quel logiciel PCB gratuit et open source est très utilisé ?", options: ["Altium Designer", "PADS", "KiCad", "OrCAD"], answer: 2, explanation: "KiCad : logiciel de CAO PCB open source, gratuit, professionnel. Aussi : EasyEDA (en ligne)." },
  { q: "Le process de fabrication d'un PCB commence par…", options: ["Le perçage", "Le dépôt de cuivre sur le substrat", "L'application du vernis épargne", "La sérigraphie"], answer: 1, explanation: "Process : dépôt cuivre → résine photosensible → insolation UV → développement → gravure → strip." },
  { q: "La gravure chimique d'un PCB utilise…", options: ["L'acide chlorhydrique pur", "Le chlorure ferrique ou persulfate d'ammonium", "L'eau oxygénée seule", "Le NaOH"], answer: 1, explanation: "FeCl3 (chlorure ferrique) ou persulfate d'ammonium : dissout le cuivre non protégé par la résine." },
  { q: "La pâte à braser est composée de…", options: ["Étain pur seulement", "Poudre d'alliage étain + flux", "Colle époxy conductrice", "Plomb et argent"], answer: 1, explanation: "Pâte à braser : poudre de SAC305 (ou Sn63/Pb37) mélangée à du flux (agent chimique désoxydant)." },
  { q: "Qu'est-ce qu'un via borgne (blind via) ?", options: ["Relie toutes les couches", "Relie la surface à une couche interne seulement", "Un via non métallisé", "Un via en cuivre plein"], answer: 1, explanation: "Via borgne : visible d'un côté seulement, relie la surface à une couche interne. Plus coûteux à fabriquer." },
  { q: "Pour une piste portant 1 A, la largeur minimale est environ…", options: ["0.1 mm", "0.5 mm", "1 mm", "5 mm"], answer: 2, explanation: "Règle pratique : ~1 mm pour 1 A (face externe, échauffement 10°C). Utiliser un calculateur IPC-2221." },
  { q: "Le 'clearance' entre deux pistes désigne…", options: ["La largeur de la piste", "L'écartement minimal entre conducteurs", "La tolérance de fabrication", "La couche de vernis"], answer: 1, explanation: "Clearance : distance minimale entre deux conducteurs, dépend de la tension (ex : 0.2 mm pour < 50 V)." },
  { q: "L'assemblage CMS par vague (wave soldering) est utilisé pour…", options: ["Les composants CMS uniquement", "Les composants THT en production de masse", "Le prototypage rapide", "Les composants BGA"], answer: 1, explanation: "Soudure à la vague : convient aux composants THT. Le PCB passe sur une vague d'étain fondu." },
  { q: "Un via enterré (buried via) est…", options: ["Visible des deux côtés", "Entre la surface et une couche interne", "Uniquement entre couches internes, invisible", "Un via plein (non percé)"], answer: 2, explanation: "Via enterré : relie deux couches internes sans atteindre la surface. Très coûteux, pour PCB denses." },
  { q: "Le pad d'un composant CMS est…", options: ["Un trou percé", "Une zone de cuivre exposée pour la soudure", "Un via", "Une marque de sérigraphie"], answer: 1, explanation: "Pad : zone de cuivre sans vernis épargne, destinée à la soudure du composant." },
  { q: "IPC-610 Classe 3 concerne…", options: ["Jouets et électronique grand public", "Électronique industrielle longue durée", "Médical, aérospatial, militaire (pas de panne admissible)", "PCB sans contrainte"], answer: 2, explanation: "Classe 3 : applications critiques où la défaillance n'est pas tolérée (médical, avionique, militaire)." },
  { q: "Un défaut 'solder bridge' (pont de soudure) est…", options: ["Une bonne soudure entre deux composants", "Un excès d'étain court-circuitant deux pads", "Un composant mal positionné", "Un via mal percé"], answer: 1, explanation: "Solder bridge : excès d'étain créant un court-circuit entre deux pads adjacents. Corriger avec tresse." },
  { q: "Un composant 'lifted pad' est…", options: ["Pad décollé du PCB lors de la dessoudure", "Pad avec trop de soudure", "Composant inversé", "Via non métallisé"], answer: 0, explanation: "Lifted pad : le pad se décolle du substrat lors d'une soudure/dessoudure excessive. Irréparable si la piste est arrachée." },
  { q: "La taille d'un composant 0402 désigne…", options: ["Sa valeur en ohms", "Ses dimensions en pouces (0.04 × 0.02 pouces)", "Son courant maximal", "Son rang dans la série E"], answer: 1, explanation: "0402 = 1.0 × 0.5 mm (format JEDEC). 0603 = 1.6×0.8 mm. 0805 = 2.0×1.25 mm." },
  { q: "Le 'footprint' d'un composant en CAO PCB désigne…", options: ["La vue 3D du composant", "L'empreinte des pads et vias sur le PCB", "La référence du composant", "La liste de matériaux (BOM)"], answer: 1, explanation: "Footprint (empreinte) : représentation des pads, vias et silkscreen d'un composant sur le PCB." },
  { q: "La BOM (Bill Of Materials) est…", options: ["Un fichier Gerber", "La liste de tous les composants du circuit", "Le plan de perçage", "Un fichier de simulation"], answer: 1, explanation: "BOM : liste de tous les composants (référence, valeur, fabricant, quantité) nécessaires à l'assemblage." },
  { q: "Quelle est la température de pic pour souder du SAC305 au four reflow ?", options: ["180°C", "217°C", "245°C", "280°C"], answer: 2, explanation: "SAC305 : liquidus à 217°C, pic recommandé à 245°C (+/-5°C). Rester < 260°C pour ne pas endommager les composants." },
  { q: "L'inspection AOI (Automated Optical Inspection) permet de…", options: ["Tester les fonctions électroniques", "Détecter les défauts visuels d'assemblage par caméra", "Programmer les microcontrôleurs", "Mesurer l'impédance des pistes"], answer: 1, explanation: "AOI : caméra + logiciel analyse les soudures, positions et polarités des composants après assemblage." },
  { q: "Le photoplotter est utilisé pour…", options: ["Photographier les défauts", "Exposer les films pour la production des couches PCB", "Mesurer l'épaisseur de cuivre", "Tester les circuits en production"], answer: 1, explanation: "Photoplotter : machine qui expose le film photomasque à partir des fichiers Gerber, pour la production." },
  { q: "Le 'netlist' en CAO électronique désigne…", options: ["La liste des réseaux (connexions électriques) du schéma", "La liste des composants", "Les fichiers de fabrication", "La règle de routage"], answer: 0, explanation: "Netlist : fichier décrivant toutes les connexions électriques du schéma, utilisé pour le routage PCB." },
  { q: "L'or chimique (ENIG) sur les pads d'un PCB sert à…", options: ["Décoration", "Protéger le cuivre de l'oxydation et améliorer la soudabilité", "Augmenter la conductivité", "Réduire l'impédance des pistes"], answer: 1, explanation: "ENIG (Electroless Nickel Immersion Gold) : finition de surface qui protège les pads et facilite la soudure." },
  { q: "Une résistance CMS 1kΩ est souvent marquée…", options: ["1K", "1000", "102", "K10"], answer: 2, explanation: "Code CMS 3 chiffres : '102' = 10 × 10² = 1000 Ω = 1 kΩ. '103' = 10 kΩ. '471' = 470 Ω." },
  { q: "Le 'DRC' (Design Rule Check) en CAO PCB vérifie…", options: ["La liste des composants", "Le respect des règles de conception (clearance, largeur piste...)", "La simulation électrique", "L'exportation Gerber"], answer: 1, explanation: "DRC : vérifie automatiquement les violations de règles de design avant fabrication (clearance, anneau de via, etc.)." },
  { q: "Le marquage CEI/CE sur un équipement indique…", options: ["Fabriqué en Chine", "Conformité aux directives européennes (sécurité, CEM)", "Certification ISO 9001", "Testé en laboratoire accrédité"], answer: 1, explanation: "Marquage CE : déclaration de conformité aux directives européennes applicables (basse tension, CEM, ROHS...)." },
  { q: "La directive RoHS interdit/limite…", options: ["Les composants importés", "Les substances dangereuses (plomb, mercure...) dans les équipements", "Les PCB à plus de 4 couches", "L'usage de résine époxy"], answer: 1, explanation: "RoHS : Restriction of Hazardous Substances. Limite Pb, Hg, Cd, Cr VI, PBDE, PBB dans les équipements électroniques." },
  { q: "Le 'pick and place' est une machine qui…", options: ["Perce les trous de vias", "Place automatiquement les composants CMS sur le PCB", "Applique la pâte à braser", "Contrôle visuellement les soudures"], answer: 1, explanation: "Pick and place : robot qui prend les composants CMS sur des bobines et les place avec précision sur la pâte à braser." },
  { q: "Un PCB double face possède…", options: ["Une seule couche de cuivre", "Deux couches de cuivre (haut et bas) reliées par des vias", "Quatre couches de cuivre", "Des couches enterrées uniquement"], answer: 1, explanation: "Double face : cuivre top + cuivre bottom. Les vias traversants permettent les connexions entre les deux faces." },
  { q: "Le flux dans la soudure joue le rôle de…", options: ["Conducteur électrique", "Agent désoxydant facilitant le mouillage de l'étain", "Isolant thermique", "Adhésif mécanique"], answer: 1, explanation: "Flux : élimine les oxydes sur le cuivre et l'étain, permettant un bon mouillage (diffusion de l'étain)." },
  { q: "La résistance thermique (RθJA) d'un composant décrit…", options: ["Sa résistance électrique à haute température", "La résistance au passage de la chaleur de la jonction à l'air ambiant", "Sa résistance mécanique", "La résistance de sa boîte (package)"], answer: 1, explanation: "RθJA (°C/W) : plus elle est faible, mieux le composant dissipe la chaleur. Importante pour le dimensionnement thermique." },
  { q: "Un pad 'non-planar' (ou tombstone) en IPC-610 Classe 3 est…", options: ["Accepté sans condition", "Accepté avec condition (angle < 15°)", "Refusé (défaut rédhibitoire)", "Toujours réparable par refusion"], answer: 2, explanation: "Classe 3 : le tombstoning (composant soulevé) est un défaut de Classe 3 = refus. Réparation requise." },
  { q: "Pour prototyper rapidement un PCB, la meilleure solution est…", options: ["Graver soi-même avec FeCl3", "Commander en ligne (JLCPCB, PCBway : 5 PCBs ~5€)", "Utiliser une maquette breadboard uniquement", "Imprimer en 3D les circuits"], answer: 1, explanation: "Fabricants en ligne comme JLCPCB ou PCBway : 5 PCBs 10×10 cm pour ~5€, livraison en ~1 semaine." },
  { q: "Le 'reflow profil' d'un four SMD définit…", options: ["La vitesse du convoyeur uniquement", "Les phases de préchauffage, montée en T°, pic et refroidissement", "La cadence de production par heure", "Le temps de séchage du flux"], answer: 1, explanation: "Profil reflow : montée lente (préchauffage activation flux), rampe vers pic (~245°C), refroidissement contrôlé (<3°C/s)." },
  { q: "Quel est le rôle du plan de masse (ground plane) sur un PCB ?", options: ["Réduire l'impédance de masse, diminuer les perturbations EMC", "Augmenter la résistance des pistes", "Servir de plan de référence visuel", "Permettre le routage automatique"], answer: 0, explanation: "Plan de masse continu : impédance quasi-nulle pour le retour de courant, blindage EMC, dissipation thermique." },
  { q: "Le format d'un composant 'SOIC-8' désigne…", options: ["Un composant THT à 8 pattes", "Un boîtier CMS Small Outline IC à 8 broches", "Un condensateur CMS de 8 µF", "Un connecteur 8 voies"], answer: 1, explanation: "SOIC-8 : Small Outline Integrated Circuit, 8 broches, pas de 1.27 mm. Format CMS courant pour les AOP, µC simples." },
  { q: "Que signifie 'DNI' ou 'DNP' sur une nomenclature PCB ?", options: ["Do Not Include / Do Not Place : composant non monté", "Diode NPN Inverse", "Dual Network Interface", "Démonter Nettement Immédiatement"], answer: 0, explanation: "DNI/DNP (Do Not Install/Place) : le composant est présent sur le PCB mais ne doit pas être soudé (option)." },
  { q: "L'anneau de cuivre autour d'un via s'appelle…", options: ["Pad", "Annular ring (couronne)", "Clearance", "Silkscreen"], answer: 1, explanation: "Annular ring : couronne de cuivre autour du via. Largeur minimale typique : 0.15 mm (PCB standard)." },
  { q: "Quelle face du PCB porte généralement les composants principaux ?", options: ["Bottom (côté soudure)", "Top (composants)", "Les deux indifféremment", "Aucune face spécifique"], answer: 1, explanation: "Top (face composants) : porte la majorité des composants. Bottom : souvent le plan de masse et quelques composants." },
  { q: "La soudure à l'étain sans plomb (SAC305) est imposée par…", options: ["La norme FR4", "La directive RoHS", "L'IPC-610 Classe 2", "Le règlement REACH uniquement"], answer: 1, explanation: "RoHS : restriction du plomb dans les équipements électroniques. SAC305 (Sn-Ag-Cu) est l'alliage sans plomb dominant." },
  { q: "Qu'est-ce qu'un 'stencil' (pochoir) en assemblage SMD ?", options: ["Un gabarit métallique percé pour déposer la pâte à braser sur les pads", "Un film pour l'insolation UV", "Un masque pour la sérigraphie", "Un filtre pour le four reflow"], answer: 0, explanation: "Stencil : feuille d'acier inoxydable (0.12-0.15 mm) percée sur les pads. Permet un dépôt précis de pâte à braser." },
  { q: "Un PCB 'flex' (flexible) utilise comme substrat…", options: ["FR4", "Polyimide (Kapton)", "Aluminium", "Céramique"], answer: 1, explanation: "PCB flex : substrat en polyimide (Kapton), souple, résistant à la chaleur. Utilisé dans smartphones, câbles plats." },
  { q: "Le 'tombstoning' est plus fréquent sur les composants…", options: ["QFP à 100 broches", "BGA", "0402 et 0201 (très petits CMS à 2 broches)", "TO-220 traversants"], answer: 2, explanation: "Plus la taille du composant est petite, plus les forces de tension de surface sont déséquilibrées → tombstoning fréquent sur 0402/0201." },
  { q: "L'inspection aux rayons X (X-Ray) en production PCB sert à…", options: ["Mesurer l'épaisseur des pistes", "Vérifier les soudures invisibles (BGA, QFN)", "Contrôler la résistance des matériaux", "Détecter les composants surchauffés"], answer: 1, explanation: "Rayons X : indispensable pour contrôler les soudures sous les boîtiers BGA et QFN où les joints ne sont pas visibles." },
  { q: "Que représente le chiffre dans 'PCB 4 couches' ?", options: ["L'épaisseur en mm", "Le nombre de couches de cuivre", "Le nombre de composants maximum", "Le nombre de faces visibles"], answer: 1, explanation: "4 couches = 4 plans de cuivre superposés (ex : Top, GND plane, VCC plane, Bottom). Meilleure intégrité signal." },
];

// ─────────────────────────────────────────────────────────────────────────────
// MATHÉMATIQUES — 60 questions
// ─────────────────────────────────────────────────────────────────────────────
const Q_MATH: QuizQuestion[] = [
  { q: "La dérivée de f(x) = x³ est…", options: ["3x", "x²", "3x²", "x³/3"], answer: 2, explanation: "(xⁿ)' = n·xⁿ⁻¹ → (x³)' = 3x²." },
  { q: "La dérivée de f(x) = sin(x) est…", options: ["-cos(x)", "cos(x)", "-sin(x)", "tan(x)"], answer: 1, explanation: "(sin x)' = cos x." },
  { q: "La règle du produit : (u·v)' = ?", options: ["u'·v'", "u'v + uv'", "u'v − uv'", "(u'v')/uv"], answer: 1, explanation: "(u·v)' = u'v + uv'." },
  { q: "La dérivée de f(x) = ln(x) est…", options: ["1/x²", "e^x", "1/x", "ln(x)/x"], answer: 2, explanation: "(ln x)' = 1/x pour x > 0." },
  { q: "(f∘g)'(x) = ?", options: ["f'(x)·g'(x)", "f'(g(x))·g'(x)", "f(g'(x))", "f'(g(x))+g'(x)"], answer: 1, explanation: "Règle de la chaîne : (f(g(x)))' = f'(g(x)) × g'(x)." },
  { q: "∫ x² dx = ?", options: ["2x + C", "x³ + C", "x³/3 + C", "3x³ + C"], answer: 2, explanation: "∫xⁿ dx = xⁿ⁺¹/(n+1) + C → ∫x² dx = x³/3 + C." },
  { q: "cos(π/2) = ?", options: ["0", "1", "-1", "√2/2"], answer: 0, explanation: "cos(90°) = 0." },
  { q: "Une suite géométrique de raison q > 1 est…", options: ["Décroissante", "Constante", "Croissante", "Convergente vers 0"], answer: 2, explanation: "q > 1 → chaque terme est multiplié par un nombre > 1 → suite croissante (si premier terme > 0)." },
  { q: "(e^(2x))' = ?", options: ["e^(2x)", "2e^(2x)", "e^(2x)/2", "2x·e^(2x)"], answer: 1, explanation: "Règle de la chaîne : (e^(2x))' = 2·e^(2x)." },
  { q: "sin²(x) + cos²(x) = ?", options: ["0", "2", "1", "sin(2x)"], answer: 2, explanation: "Identité fondamentale : sin²x + cos²x = 1." },
  { q: "(cos x)' = ?", options: ["sin x", "-sin x", "cos x", "-cos x"], answer: 1, explanation: "(cos x)' = -sin x." },
  { q: "La dérivée d'une constante est…", options: ["La constante elle-même", "1", "0", "La constante ÷ x"], answer: 2, explanation: "La dérivée d'une constante k est toujours 0." },
  { q: "(u/v)' = ?", options: ["u'v + uv'", "(u'v − uv') / v²", "u'/v'", "(u'v + uv') / v²"], answer: 1, explanation: "Règle du quotient : (u/v)' = (u'v − uv') / v²." },
  { q: "f'(x) > 0 sur [a,b] signifie que f est…", options: ["Décroissante", "Constante", "Croissante", "Concave"], answer: 2, explanation: "f' > 0 ↔ f croissante. f' < 0 ↔ f décroissante." },
  { q: "(√x)' = ?", options: ["2√x", "1/(2√x)", "√x/2", "2x^(3/2)"], answer: 1, explanation: "(x^½)' = ½ x^(-½) = 1/(2√x)." },
  { q: "∫ sin(x) dx = ?", options: ["cos(x) + C", "-cos(x) + C", "sin(x) + C", "-sin(x) + C"], answer: 1, explanation: "∫sin(x)dx = -cos(x) + C." },
  { q: "∫ e^x dx = ?", options: ["e^x + C", "e^x/x + C", "x·e^x + C", "e^(x+1) + C"], answer: 0, explanation: "∫e^x dx = e^x + C. L'exponentielle est sa propre primitive." },
  { q: "sin(0) = ?", options: ["1", "0", "-1", "∞"], answer: 1, explanation: "sin(0) = 0. cos(0) = 1." },
  { q: "(3x² + 2x − 5)' = ?", options: ["6x + 2", "3x + 2", "6x² + 2", "6x − 5"], answer: 0, explanation: "(3x²)' = 6x, (2x)' = 2, (5)' = 0 → f'(x) = 6x + 2." },
  { q: "tan(x) = ?", options: ["sin(x)/cos(x)", "cos(x)/sin(x)", "1/sin(x)", "cos²(x) - sin²(x)"], answer: 0, explanation: "tan(x) = sin(x)/cos(x)." },
  { q: "La suite un = 3n + 1 est…", options: ["Géométrique", "Arithmétique de raison 3", "Décroissante", "Constante"], answer: 1, explanation: "Suite arithmétique : chaque terme augmente d'une raison constante r = 3." },
  { q: "Le terme général d'une suite arithmétique est…", options: ["un = u0 × qⁿ", "un = u0 + n×r", "un = u0 × rⁿ", "un = u0 / n"], answer: 1, explanation: "Suite arithmétique : un = u0 + n×r (ou u1 + (n-1)×r selon la convention)." },
  { q: "La limite de (1/n) quand n → +∞ est…", options: ["+∞", "1", "0", "-∞"], answer: 2, explanation: "1/n → 0 quand n → +∞." },
  { q: "∫₀^1 x dx = ?", options: ["0", "1/2", "1", "2"], answer: 1, explanation: "∫₀¹ x dx = [x²/2]₀¹ = 1/2 − 0 = 1/2." },
  { q: "La dérivée de f(x) = e^x est…", options: ["x·e^(x-1)", "e^x", "e^(x+1)", "1/e^x"], answer: 1, explanation: "(e^x)' = e^x. Propriété fondamentale : l'exponentielle est sa propre dérivée." },
  { q: "(sin(3x))' = ?", options: ["sin(3)", "cos(3x)", "3cos(3x)", "-3sin(3x)"], answer: 2, explanation: "Règle de la chaîne : (sin(3x))' = cos(3x) × 3 = 3cos(3x)." },
  { q: "La valeur de f'(x0) représente…", options: ["L'ordonnée de f en x0", "La pente de la tangente à la courbe en x0", "L'aire sous la courbe", "Le maximum de f"], answer: 1, explanation: "f'(x0) = coefficient directeur (pente) de la tangente à la courbe en x0." },
  { q: "Un extremum de f est atteint quand…", options: ["f(x) = 0", "f'(x) = 0 (avec changement de signe)", "f'(x) = 1", "f''(x) = 0"], answer: 1, explanation: "Extremum (max ou min) : f'(x) = 0 avec changement de signe de f'." },
  { q: "(ln(2x))' = ?", options: ["1/x", "2/x", "1/(2x)", "ln(2)/x"], answer: 0, explanation: "Règle de la chaîne : (ln(2x))' = 1/(2x) × 2 = 1/x." },
  { q: "∫ 1/x dx = ?", options: ["x² + C", "-1/x² + C", "ln|x| + C", "1/x² + C"], answer: 2, explanation: "∫(1/x)dx = ln|x| + C pour x ≠ 0." },
  { q: "cos(π) = ?", options: ["0", "1", "-1", "√2/2"], answer: 2, explanation: "cos(π) = cos(180°) = -1." },
  { q: "sin(π/2) = ?", options: ["0", "1/2", "1", "√2/2"], answer: 2, explanation: "sin(π/2) = sin(90°) = 1." },
  { q: "La dérivée de x^4 est…", options: ["4x³", "x^5/5", "4x^5", "x^3/4"], answer: 0, explanation: "(x^4)' = 4·x^(4-1) = 4x³." },
  { q: "f(x) = x² − 4x + 3. f'(x) = ?", options: ["2x − 4", "x² − 4", "2x + 4", "x − 4"], answer: 0, explanation: "f'(x) = 2x − 4." },
  { q: "f'(2) = 0 et f' change de signe de + à −. En x=2, f a un…", options: ["Minimum", "Maximum", "Point d'inflexion", "Zéro"], answer: 1, explanation: "f' passe de + à − → maximum local en x = 2." },
  { q: "La suite géométrique u0=2, q=3. u3 = ?", options: ["8", "18", "54", "162"], answer: 2, explanation: "u3 = u0 × q³ = 2 × 27 = 54." },
  { q: "∫₀^π sin(x) dx = ?", options: ["0", "1", "2", "π"], answer: 2, explanation: "[-cos(x)]₀^π = -cos(π) + cos(0) = 1 + 1 = 2." },
  { q: "(e^(-x))' = ?", options: ["e^(-x)", "-e^(-x)", "e^x", "-1/e^x"], answer: 1, explanation: "(e^(-x))' = -1 × e^(-x) = -e^(-x) (règle de la chaîne)." },
  { q: "sin(2x) = ?", options: ["2sin(x)", "2sin(x)cos(x)", "sin(x)cos(x)", "2cos(x)"], answer: 1, explanation: "Formule double angle : sin(2x) = 2sin(x)cos(x)." },
  { q: "∫ cos(x) dx = ?", options: ["-sin(x) + C", "sin(x) + C", "cos(x) + C", "-cos(x) + C"], answer: 1, explanation: "∫cos(x)dx = sin(x) + C." },
  { q: "La dérivée de f(x) = 5 est…", options: ["5", "1", "0", "5x"], answer: 2, explanation: "Dérivée d'une constante = 0." },
  { q: "(x × e^x)' = ?", options: ["e^x", "x·e^x", "(x+1)·e^x", "x²·e^x"], answer: 2, explanation: "Règle du produit : (x)'·e^x + x·(e^x)' = e^x + x·e^x = (x+1)e^x." },
  { q: "f(x) = 1/x = x^(-1). f'(x) = ?", options: ["1/x²", "-1/x²", "ln(x)", "-x^(-2)"], answer: 1, explanation: "(x^(-1))' = -1·x^(-2) = -1/x²." },
  { q: "La suite arithmétique u0=10, r=-2. u5 = ?", options: ["0", "2", "20", "-10"], answer: 0, explanation: "u5 = u0 + 5×r = 10 + 5×(-2) = 10 - 10 = 0." },
  { q: "cos(2x) = ?", options: ["2cos²(x) − 1", "cos²(x) − sin²(x)", "1 − 2sin²(x)", "Toutes ces réponses"], answer: 3, explanation: "cos(2x) = cos²x − sin²x = 2cos²x − 1 = 1 − 2sin²x : toutes les formes sont équivalentes." },
  { q: "∫₁^e (1/x) dx = ?", options: ["0", "1", "e", "ln(e)"], answer: 1, explanation: "[ln(x)]₁^e = ln(e) − ln(1) = 1 − 0 = 1." },
  { q: "(x² · sin(x))' = ?", options: ["2x·sin(x) + x²·cos(x)", "2x·sin(x)", "x²·cos(x)", "2x·cos(x)"], answer: 0, explanation: "Produit : 2x·sin(x) + x²·cos(x)." },
  { q: "La dérivée de f(x) = √(x²+1) est…", options: ["1/(2√(x²+1))", "x/√(x²+1)", "2x/√(x²+1)", "√(x²+1)/x"], answer: 1, explanation: "f'(x) = 1/(2√(x²+1)) × 2x = x/√(x²+1) (règle de la chaîne)." },
  { q: "sin(π/6) = ?", options: ["√3/2", "1/2", "√2/2", "1"], answer: 1, explanation: "sin(30°) = 1/2. Valeurs remarquables : sin(30°)=1/2, sin(45°)=√2/2, sin(60°)=√3/2." },
  { q: "cos(π/3) = ?", options: ["√3/2", "1/2", "√2/2", "0"], answer: 1, explanation: "cos(60°) = 1/2." },
  { q: "La limite de (e^x) quand x → +∞ est…", options: ["0", "1", "e", "+∞"], answer: 3, explanation: "L'exponentielle tend vers +∞ quand x → +∞." },
  { q: "Quelle est la primitive de f(x) = 3 ?", options: ["3x + C", "3/x + C", "x³ + C", "0 + C"], answer: 0, explanation: "∫3 dx = 3x + C (intégrale d'une constante)." },
  { q: "(ln(x²))' = ?", options: ["1/x²", "2/x", "2x/x²", "2·ln(x)"], answer: 1, explanation: "ln(x²) = 2·ln(x) → (2·ln(x))' = 2/x. Ou règle de la chaîne : 2x/x² = 2/x." },
  { q: "f(x) = x³ − 3x. f'(x) = 0 pour x = ?", options: ["x = 0 uniquement", "x = 1 et x = -1", "x = 3 et x = -3", "x = 0 et x = 3"], answer: 1, explanation: "f'(x) = 3x² − 3 = 0 → x² = 1 → x = ±1." },
  { q: "La tangente à f(x) = x² en x = 2 a une pente de…", options: ["2", "4", "8", "1/4"], answer: 1, explanation: "f'(x) = 2x → f'(2) = 4. La pente de la tangente en x=2 est 4." },
  { q: "∫₀^2 x² dx = ?", options: ["4/3", "8/3", "4", "8"], answer: 1, explanation: "[x³/3]₀^2 = 8/3 − 0 = 8/3." },
  { q: "(sin(x)/cos(x))' = 1/cos²(x). Cette dérivée est celle de…", options: ["sin(x)", "cos(x)", "tan(x)", "1/sin(x)"], answer: 2, explanation: "(tan(x))' = 1/cos²(x) = sec²(x)." },
  { q: "La somme des n premiers termes d'une suite arithmétique est…", options: ["Sn = n × r", "Sn = (u1 + un) × n/2", "Sn = u1 × (qⁿ-1)/(q-1)", "Sn = n × u1"], answer: 1, explanation: "Sn = (u1 + un) × n/2 : demi-somme des extrêmes × nombre de termes." },
  { q: "Quelle est la dérivée de f(x) = 4x³ − 2x + 7 ?", options: ["12x² − 2", "4x² − 2", "12x³ − 2x", "4x² − 2x + 7"], answer: 0, explanation: "f'(x) = 12x² − 2." },
  { q: "La limite de (xⁿ) quand x → 0 (n > 0) est…", options: ["1", "n", "0", "+∞"], answer: 2, explanation: "xⁿ → 0 quand x → 0 (pour n > 0)." },
];

// ─────────────────────────────────────────────────────────────────────────────
// QUIZ CATEGORIES
// ─────────────────────────────────────────────────────────────────────────────
export const QUIZ_CATEGORIES: QuizCategory[] = [
  {
    id: "electronics",
    label: "Électronique",
    emoji: "⚡",
    color: "from-violet-600 to-blue-600",
    questions: Q_ELECTRONICS,
    cheatSheet: {
      title: "Formules essentielles",
      rows: [
        { formula: "U = R × I", label: "Loi d'Ohm", note: "U en V, R en Ω, I en A" },
        { formula: "P = U × I", label: "Puissance", note: "aussi P = R×I² ou U²/R" },
        { formula: "Req = R1 + R2", label: "Résistances série" },
        { formula: "1/Req = 1/R1 + 1/R2", label: "Résistances parallèle" },
        { formula: "Vout = Vin × R2/(R1+R2)", label: "Diviseur de tension", note: "R2 côté GND" },
        { formula: "τ = R × C", label: "Constante de temps RC", note: "63% à τ, 99% à 5τ" },
        { formula: "R_LED = (Vcc − Vf) / I", label: "Résistance LED" },
        { formula: "Ic = β × Ib", label: "Transistor BJT", note: "β = gain (50–500)" },
        { formula: "Av = −R2/R1", label: "AOP inverseur" },
        { formula: "fc = 1/(2π×R×C)", label: "Filtre RC : fréquence de coupure" },
      ],
    },
  },
  {
    id: "maintenance",
    label: "Maintenance",
    emoji: "🔧",
    color: "from-orange-600 to-red-600",
    questions: Q_MAINTENANCE,
    cheatSheet: {
      title: "Aide-mémoire maintenance",
      rows: [
        { formula: "Voltmètre → parallèle", label: "Mesure de tension" },
        { formula: "Ampèremètre → série", label: "Mesure de courant" },
        { formula: "T = 1/f", label: "Période / Fréquence" },
        { formula: "Ueff = Umax / √2", label: "Tension efficace (AC)" },
        { formula: "5 règles : Séparer·Condamner·VAT·Terre·Baliser", label: "Sécurité hors tension" },
        { formula: "IP XY", label: "X=solides (0-6), Y=liquides (0-9)" },
        { formula: "B1=hors tension, B2=chargé, BR=dépannage", label: "Habilitations BT" },
        { formula: "Soudure bonne → brillante et conique", label: "Qualité soudure" },
      ],
    },
  },
  {
    id: "fabrication",
    label: "Fabrication",
    emoji: "🏭",
    color: "from-green-600 to-teal-600",
    questions: Q_FABRICATION,
    cheatSheet: {
      title: "Aide-mémoire fabrication",
      rows: [
        { formula: "THT → patte dans trou | CMS → surface", label: "Types de montage" },
        { formula: "Reflow → four ~245°C (SAC305)", label: "Assemblage CMS" },
        { formula: "Via → trou métallisé inter-couches", label: "PCB multicouche" },
        { formula: "Gerber → fichiers FAB", label: "GTL/GBL + DRL + GTS/GBS" },
        { formula: "IPC-610 : Classe 1/2/3", label: "1=grand public, 3=critique" },
        { formula: "Abs. Max Ratings → NE JAMAIS DÉPASSER", label: "Datasheet" },
        { formula: "0402 = 1.0×0.5 mm", label: "Tailles CMS" },
        { formula: "RoHS → sans plomb imposé", label: "Directive européenne" },
      ],
    },
  },
  {
    id: "math",
    label: "Mathématiques",
    emoji: "∂",
    color: "from-blue-600 to-cyan-600",
    questions: Q_MATH,
    cheatSheet: {
      title: "Table de dérivation & intégration",
      rows: [
        { formula: "(xⁿ)' = n·xⁿ⁻¹", label: "Puissance", note: "(x³)'=3x²" },
        { formula: "(eˣ)' = eˣ", label: "Exponentielle" },
        { formula: "(ln x)' = 1/x", label: "Logarithme" },
        { formula: "(sin x)' = cos x", label: "Sinus" },
        { formula: "(cos x)' = −sin x", label: "Cosinus" },
        { formula: "(u·v)' = u'v + uv'", label: "Produit" },
        { formula: "(u/v)' = (u'v − uv') / v²", label: "Quotient" },
        { formula: "(f(g(x)))' = f'(g(x))·g'(x)", label: "Composée" },
        { formula: "∫xⁿ dx = xⁿ⁺¹/(n+1) + C", label: "Primitive puissance" },
        { formula: "sin²x + cos²x = 1", label: "Identité trigo" },
      ],
    },
  },
  {
    id: "mixed",
    label: "Défi mixte",
    emoji: "🎯",
    color: "from-pink-600 to-purple-600",
    questions: [], // Filled dynamically
    cheatSheet: {
      title: "Rappels essentiels",
      rows: [
        { formula: "U = R × I", label: "Loi d'Ohm" },
        { formula: "P = U × I", label: "Puissance" },
        { formula: "(xⁿ)' = n·xⁿ⁻¹", label: "Dérivée puissance" },
        { formula: "(sin x)' = cos x", label: "Dérivée sin" },
        { formula: "τ = R × C", label: "Constante RC" },
        { formula: "Voltmètre → parallèle", label: "Mesure tension" },
        { formula: "Via → trou métallisé PCB", label: "Fabrication" },
        { formula: "IP XY → protection", label: "Indice IP" },
      ],
    },
  },
];

// Fill mixed with all questions from other categories
const allQ = QUIZ_CATEGORIES.filter(c => c.id !== "mixed").flatMap(c => c.questions);
QUIZ_CATEGORIES.find(c => c.id === "mixed")!.questions = allQ;
